LIKE|LIKE
RLIKE|regexp_like
REGEXP|regexp_like
map|map
struct|row
named_struct|(待确认)
array|array
create_union|(待确认)
round|round
round|round
bround|未实现银行家舍入法，需自定义udf函数实现
floor|floor
rand|rand
exp|exp
ln|ln
log10|log10
log2|log2
log|log
pow|pow
power|power
sqrt|sqrt
bin|to_base
hex|(待确认)
unhex|(待确认)
conv|(待确认)
abs|abs(DOUBLE a)
pmod|mod
sin|sin
asin|asin
cos|cos
acos|acos
tan|tan
atan|atan
degrees|degrees
radians|radians
positive|(待确认)
negative|(待确认)
sign|sign
e|e()
pi|pi()
factorial|(待确认)
cbrt|cbrt
shiftleft|(待确认)
shiftright|(待确认)
shiftrightunsigned|(待确认)
greatest|(待确认)
least|(待确认)
width_bucket|width_bucket
size|(待确认)
size|(待确认)
map_keys|map_keys
map_values|map_values
array_contains|contains
sort_array|array_sort
binary|binary
cast|cast
from_unixtime|from_unixtime
unix_timestamp|(待确认)
unix_timestamp|to_unixtime
unix_timestamp|(待确认)
to_date|to_date
year|year
quarter|quarter
month|month
day dayofmonth|day dayofmonth
hour|hour
minute|minute
second|second
weekofyear|weekofyear
extract|extract
datediff|datediff
date_add|(待确认)
date_sub|(待确认)
from_utc_timestamp|(待确认)
to_utc_timestamp|(待确认)
current_date|current_date
current_timestamp|current_timestamp
add_months|(待确认)
last_day|(待确认)
next_day|(待确认)
trunc|date_trunc
months_between|(待确认)
date_format|date_format
if|if
isnull|a is null
isnotnull|a is not null
nvl|(待确认)
COALESCE|COALESCE
CASE a WHEN b THEN c [WHEN d THEN e]* [ELSE f] END|CASE a WHEN b THEN c [WHEN d THEN e]* [ELSE f] END
CASE WHEN a THEN b [WHEN c THEN d]* [ELSE e] END|CASE WHEN a THEN b [WHEN c THEN d]* [ELSE e] END
nullif|nullif
assert_true|try,但不抛异常返回null
base64|(待确认)
character_length|(待确认)
chr|double
concat|binary
context_ngrams|(待确认)
concat_ws|(待确认)
decode|(待确认)
elt|(待确认)
encode|(待确认)
field|(待确认)
find_in_set|(待确认)
format_number|(待确认)
get_json_object|(待确认)
in_file|(待确认)
instr|strpos
length|length
locate|position
lower|lower
lpad|lpad
ltrim|ltrim
ngrams|ngrams
octet_length|(待确认)
parse_url|参考URL函数章节
printf|format
quote|(待确认)
regexp_extract|regexp_extract
regexp_replace|regexp_replace
repeat|(待确认)
replace|replace
reverse|reverse
rpad|rpad
rtrim|rtrim
sentences|(待确认)
space|(待确认)
split|split
str_to_map|split_to_map
substr substring|substr
substr substring|substr
substring_index|(待确认)
translate|replace
trim|trim
unbase64|(待确认)
upper|upper
initcap|(待确认)
levenshtein|levenshtein_distance
soundex|无，需要自定义udf
mask|无
mask_first_n|无
mask_last_n|无
mask_show_first_n|无
mask_show_last_n|无
mask_hash|char
java_method|无
reflect|无
hash|无
current_user|current_user
logged_in_user|无
current_database|无
md5|md5
sha1 sha|sha1
crc32|crc32
sha2|sha256，sha512
aes_encrypt|无
aes_decrypt|无
surrogate_key|无
xpath|无
get_json_object|get_json_object
count|count
sum|sum
avg|avg
min|min
max|max
variance var_pop|variance var_pop
var_samp|var_samp
stddev_pop|stddev_pop
stddev_samp|stddev_samp
covar_pop|covar_pop
covar_samp|covar_samp
corr|corr
percentile|无
percentile|无
percentile_approx|approx_percentile
percentile_approx|approx_percentile
regr_avgx|待确认
regr_avgy|待确认
regr_count|待确认
regr_intercept|待确认
regr_r2|待确认
regr_slope|待确认
regr_sxx|待确认
regr_sxy|待确认
regr_syy|待确认
histogram_numeric|numeric_histogram
collect_set|array_distinct
collect_list|array_agg
ntile|待确认
explode|待确认
explode|待确认
posexplode|待确认
inline|待确认
stack|待确认
json_tuple|待确认
parse_url_tuple|待确认
