--修改表名称
ALTER TABLE TABLE_NAME RENAME TO NEW_TABLE_NAME;

--修改表属性
--HUBBLE不支持
ALTER TABLE TABLE_NAME SET ;

--增加/删除分区
--HUBBLE不支持
ALTER TABLE PAGE_VIEW ADD PARTITION (DT='2008-08-08', COUNTRY='US') LOCATION '/PATH/TO/US/PART080808';

--HUBBLE不支持
ALTER TABLE TABLE_NAME_2 EXCHANGE PARTITION (PARTITION_SPEC) WITH TABLE TABLE_NAME_1;