--INSERT INTO TABLE TABLENAME [PARTITION (PARTCOL1[=VAL1], PARTCOL2[=VAL2] ...)] VALUES VALUES_ROW [, VALUES_ROW ...]

--HUBBLE不支持
INSERT INTO TABLE TEST(ID, NAME) VALUES(1, 'AAAA');

INSERT INTO TEST(ID, NAME) VALUES(1, 'AAAA');

--HUBBLE不支持
INSERT INTO TABLE TEST VALUES(1, 'AAAA');

INSERT INTO TEST VALUES(1, 'AAAA');

INSERT INTO TEST VALUES(1, 'AAAA'), ('222', 'BBB');

--HUBBLE不支持
INSERT INTO TABLE TEST SELECT * FROM TEST1;

INSERT INTO TEST SELECT * FROM TEST1;

--HUBBLE不支持
INSERT OVERWRITE TABLE T12 SELECT * FROM T11;

INSERT INTO TABLE TEST PARTITION(DT='20180210') SELECT * FROM T1;

INSERT INTO TABLE TEST PARTITION (DT='2014-09-23') VALUES ('111', '222'), ('222', '333');
